apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ela-deepshare
    namespace: default
  name: ela-deepshare
spec:
  replicas: 2
  selector:
    name: ela-deepshare
  template:
    metadata:
      labels:
         name: ela-deepshare
    spec:
      containers:
      - name: es
        image: r.fds.so:5000/elasticsearch:1.0
        env:
          - name: "CLUSTER_NAME"
            value: "deepshare"
          - name: "SELECTOR"
            value: "name=deepshare"
          - name: "NAMESPACE"
            value: "default"
        ports:
        - name: es
          containerPort: 9200
        - name: es-transport
          containerPort: 9300
        volumeMounts:
        - name: apiserver-secret
          mountPath: /etc/apiserver-secret
          readOnly: true
      volumes:
      - name: apiserver-secret
        secret:
          secretName: apiserver-secret
