apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch-logging
  name: elasticsearch-logging
spec:
  ports:
  - name: ""
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30200
  type: NodePort
  selector:
    name: elasticsearch-logging
