apiVersion: v1
kind: Secret
metadata:
  name: apiserver-secret
  namespace: default
data:
  token: "cWRqei10b2tlbi1rOHMK"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch-logging
  name: elasticsearch-logging
spec:
  ports:
  - name: ""
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30200
  type: NodePort
  selector:
    name: elasticsearch-logging

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ela-deepshare
    namespace: default
  name: ela-deepshare
spec:
  replicas: 2
  selector:
    name: ela-deepshare
  template:
    metadata:
      labels:
         name: ela-deepshare
    spec:
      containers:
      - name: es
        image: r.fds.so:5000/elasticsearch:1.0
        env:
          - name: "CLUSTER_NAME"
            value: "deepshare"
          - name: "SELECTOR"
            value: "name=deepshare"
          - name: "NAMESPACE"
            value: "default"
        ports:
        - name: es
          containerPort: 9200
        - name: es-transport
          containerPort: 9300
        volumeMounts:
        - name: apiserver-secret
          mountPath: /etc/apiserver-secret
          readOnly: true
      volumes:
      - name: apiserver-secret
        secret:
          secretName: apiserver-secret

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kibana-logging
  name: kibana-controller
spec:
  replicas: 1
  selector:
    name: kibana-logging
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        name: kibana-logging
    spec:
      containers:
      - image: r.fds.so:5000/kibana:4.1.2
        env:
        - name: ELASTICSEARCH_URL
          value: http://k8s-fl-4626982f4d04ab.chinacloudapp.cn:9200
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: kibana-port
          protocol: TCP
      nodeSelector:
        env: "production"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: kibana
  name: kibana
spec:
  ports:
  - name: ""
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30601
  type: NodePort
  selector:
    name: kibana-logging
