apiVersion: v1beta1
kind: Service
id: elasticsearch-logging
port: 9200
publicIPs: [172.18.0.13, 172.18.0.14, 172.18.0.21, 172.18.0.22, 172.18.0.20, 172.18.0.28, 172.18.0.29, 172.18.0.30]
containerPort: 9200
labels:
  name: elasticsearch-logging
  kubernetes.io/cluster-service: "true"
selector:
  name: elasticsearch-logging
