apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    name: elasticsearch-logging
  name: ela-controller
  namespace: default
spec:
  replicas: 1
  selector:
    name: elasticsearch-logging
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        name: elasticsearch-logging
    spec:
      containers:
      - image: r.fds.so:5000/elasticsearch:1.1
        name: elasticsearch-logging
        ports:
        - containerPort: 9200
          name: es-port
          protocol: TCP
        - containerPort: 9300
          name: es-port1
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: es-persistent-storage
        - mountPath: /backups
          name: es-backups
      nodeSelector:
        env: "production"
      restartPolicy: Always
      volumes:
      - awsElasticBlockStore: null
        emptyDir: null
        name: es-persistent-storage
      - awsElasticBlockStore: null
        emptyDir: null
        hostPath:
          path: /backups/backups
        name: es-backups
