apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    name: kibana-logging
  name: kibana-logging-controller
  namespace: default
spec:
  replicas: 1
  selector:
    name: kibana-logging
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubernetes.io/cluster-service: "true"
        name: kibana-logging
    spec:
      containers:
      - capabilities: {}
        env:
        - name: ES_SCHEME
          value: http
        - name: ES_HOST
          value: '"+window.location.hostname+":9200'
        image: r.fds.so:5000/kibana:1.2
        imagePullPolicy: IfNotPresent
        name: kibana-logging
        ports:
        - containerPort: 80
          name: kibana-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: "20150710"
      restartPolicy: Always
      volumes: null
