apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kibana-logging
  name: kibana-controller
spec:
  replicas: 1
  selector:
    name: kibana-logging
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        name: kibana-logging
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://k8s-fl-4626982f4d04ab.chinacloudapp.cn:9200
        image: r.fds.so:5000/kibana:4.1.2
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: kibana-port
          protocol: TCP
      nodeSelector:
        env: "production"
