apiVersion: v1
kind: Service
metadata:
  labels:
    name: kibana
  name: kibana
spec:
  ports:
  - name: ""
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30601
  type: NodePort
  selector:
    name: kibana-logging
