apiVersion: v1
kind: Service
metadata:
  labels:
    name: ds
  name: ds
spec:
  ports:
  - name: "web"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "web-8000"
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ds
  type: ClusterIP

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ds
  name: ds
spec:
  replicas: 1
  selector:
    name: ds
  template:
    metadata:
      labels:
        app: ds
        name: ds
    spec:
      containers:
      - env:
        - name: _DEEPSHARE_URL_BASE_HOST
          value: http://fds.so
        - name: _DEEPSHARE_URL_BASE_PORT
          value: "8080"
        image: r.fds.so:5000/deepshare:201509304
        name: ds
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
