apiVersion: v1
kind: Pod
metadata:
  labels:
    name: proxy
  name: proxy-pod1
  namespace: default
spec:
  nodeName: 172.18.0.20
  containers:
  - image: r.fds.so:5000/nginx:1.9.5
    name: proxy8080
    ports:
    - containerPort: 8080
      hostPort: 30080
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/default.conf
      name: conf8080
  - image: r.fds.so:5000/nginx:1.9.5
    name: proxy8000
    ports:
    - containerPort: 8000
      hostPort: 30081
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/default.conf
      name: conf8000
  - image: r.fds.so:5000/nginx:1.9.5
    name: proxy80
    ports:
    - containerPort: 80
      hostPort: 31080
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/default.conf
      name: conf80
  volumes:
  - hostPath:
    path: /mnt/resource/nginx8080.conf
    name: conf8080
  - hostPath:
    path: /mnt/resource/nginx8000.conf
    name: conf8000
  - hostPath:
    path: /mnt/resource/nginx80.conf
    name: conf80
