apiVersion: v1
kind: Service
metadata:
  labels:
    name: ds-proxy8080
  name: ds-proxy8080
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30880
  type: NodePort
  selector:
    name: ds-proxy8080

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ds-proxy8080
  name: ds-proxy8080
spec:
  replicas: 1
  selector:
    name: ds-proxy8080
  template:
    metadata:
      labels:
        name: ds-proxy8080
    spec:
      containers:
      - image: r.fds.so:5000/proxy8080:201510122
        name: ds-proxy8080
        ports:
        - containerPort: 8080
          protocol: TCP
