apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: registry2-azure
  name: registry2-azure
  namespace: default
spec:
  replicas: 1
  selector:
    name: registry2-azure
  template:
    metadata:
      labels:
        name: registry2-azure
    spec:
      containers:
      - image: r.fds.so:5000/registry-azure:20150615
        name: registry2-azure
        ports:
        - containerPort: 5000
          protocol: TCP
      nodeSelector:
        env: production
