apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: registry2-azure
  name: registry2-azure
  namespace: default
spec:
  replicas: 2
  selector:
    name: registry2-azure
  template:
    metadata:
      labels:
        name: registry2-azure
    spec:
      containers:
      - image: kevinliuzhong/registry-azure:20150615
        name: registry2-azure
        ports:
        - containerPort: 5000
          protocol: TCP
      nodeName: 172.18.0.14

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: registry2-azure
  name: registry2-azure
spec:
  ports:
  - name: "web"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30050
  type: NodePort
  selector:
    name: registry2-azure
