apiVersion: v1beta3
kind: Service
metadata:
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    name: kube-dns
  name: kube-dns
  namespace: default
spec:
  portalIP: 10.1.0.3
  ports:
  - name: ""
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
