apiVersion: v1
kind: Service
metadata:
  labels:
    name: ss
  name: ss
spec:
  ports:
  - name: ""
    port: 8123
    protocol: TCP
    targetPort: 8123
    nodePort: 30023
  type: NodePort
  selector:
    name: ss
