apiVersion: v1
kind: Pod
metadata:
  labels:
    name: deepshare
    uses: redis-master
  name: deepshare-pod2
  namespace: default
spec:
  nodeSelector:
    deepshare: pod2
    env: production
  containers:
  - capabilities: {}
    env:
    - name: _DEEPSHARE_URL_BASE_HOST
      value: http://k8s-fl-2e70e0aedce405.chinacloudapp.cn
    - name: _DEEPSHARE_URL_BASE_PORT
      value: "8080"
    image: r.fds.so:5000/deepshare:20150912
    name: deepshare
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    - containerPort: 8000
      hostPort: 8000
      protocol: TCP
