apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare
  name: deepshare
spec:
  ports:
  - name: "web"
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30081
  - name: "web-8000"
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  selector:
    app: deepshare
  type: NodePort
