apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare
  name: deepshare-controller-rolling
spec:
  replicas: 2
  selector:
    name: deepshare
  template:
    metadata:
      labels:
        app: deepshare
        name: deepshare
        uses: redis-master
    spec:
      containers:
      - capabilities: {}
        env:
        - name: _DEEPSHARE_URL_BASE_HOST
          value: http://http://kube-a6c3673ca3c64c.cloudapp.net
        - name: _DEEPSHARE_URL_BASE_PORT
          value: "8080"
        image: kevinliuzhong/deepshare
        imagePullPolicy: IfNotPresent
        name: deepshare
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: logfile
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /tmp/log
        name: logfile
