apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare-dash
  name: deepshare-dash
spec:
  ports:
  - name: ""
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30084
  type: NodePort
  selector:
    name: deepshare-dash

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare-dash
  name: ds-dash-controller
spec:
  replicas: 1
  selector:
    name: deepshare-dash
  template:
    metadata:
      labels:
        name: deepshare-dash
    spec:
      containers:
      - image: r.fds.so:5000/jekyll:stable
        name: deepshare-website1
        ports:
        - containerPort: 4000
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/jekyll
          name: website
      nodeName: 172.18.0.6
      volumes:
      - hostPath:
          path: /mnt/resource/webserver/deepshare_website_v2.0
        name: website
