apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare-webserver
  name: deepshare-webserver
spec:
  ports:
  - name: "http"
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30083
  type: NodePort
  selector:
    name: deepshare-webserver

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare-server
  name: deepshare-webserver
spec:
  replicas: 1
  selector:
    name: deepshare-webserver
  template:
    metadata:
      labels:
        name: deepshare-webserver
    spec:
      containers:
      - image: r.fds.so:5000/dswebserver:20150927
        name: deepshare-webserver
        ports:
        - containerPort: 8081
          protocol: TCP
