apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  selector:
    name: mongo
  template:
    metadata:
      labels:
        app: mongo
        name: mongo
    spec:
      containers:
      - capabilities: {}
        image: r.fds.so:5000/mongo
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: redis-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        redis: "production"
      restartPolicy: Always
      volumes:
      - awsElasticBlockStore: null
        emptyDir: null
        hostPath:
          path: /mnt/resource/mongo
        name: redis-data
