apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
  - name: ""
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30017
  type: NodePort
  selector:
    name: mongo
