apiVersion: v1
kind: Pod
metadata:
  labels:
    name: deepshare
    uses: redis-master
  name: deepshare-pod3
  namespace: default
spec:
  nodeName: 172.18.0.13
  containers:
  - env:
    - name: _DEEPSHARE_URL_BASE_HOST
      value: http://fds.so
    - name: _DEEPSHARE_URL_BASE_PORT
      value: "8080"
    image: r.fds.so:5000/deepshare:201509191
    name: deepshare
    ports:
    - containerPort: 8080
      hostPort: 30080
      protocol: TCP
    - containerPort: 8000
      hostPort: 30081
      protocol: TCP
