apiVersion: v1
kind: Pod
metadata:
  labels:
    name: deepshare
    uses: redis-master
  name: deepshare-pod4
  namespace: default
spec:
  nodeName: 172.18.0.20
  containers:
  - env:
    - name: _DEEPSHARE_URL_BASE_HOST
      value: http://fds.so
    - name: _DEEPSHARE_URL_BASE_PORT
      value: "8080"
    image: r.fds.so:5000/deepshare:201509304
    name: deepshare
    ports:
    - containerPort: 8080
      hostPort: 10080
      protocol: TCP
    - containerPort: 8000
      hostPort: 10081
      protocol: TCP
    - containerPort: 80
      hostPort: 11080
      protocol: TCP
