apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: redis-master
  name: redis-master-controller
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        app: redis
        name: redis-master
    spec:
      containers:
      - capabilities: {}
        image: qdco.chinacloudapp.cn:5000/redis
        imagePullPolicy: IfNotPresent
        name: redis-master
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /redis-data
          name: redis-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        redis: "true"
      restartPolicy: Always
      volumes:
      - awsElasticBlockStore: null
        emptyDir: null
        hostPath:
          path: /mnt/resource/redis
        name: redis-data
